export { default as Navbar } from '@/Components/Section/Navbar';
export { default as Hero } from '@/Components/Section/Hero';
export { default as About } from '@/Components/Section/About/About';
export { default as Experience } from '@/Components/Section/About/Experience';
export { default as Education } from '@/Components/Section/About/Education';
export { default as Organization } from '@/Components/Section/About/Organization';
export { default as Work } from '@/Components/Section/About/Work';
export { default as Skills } from '@/Components/Section/Skills';
export { default as Projects } from '@/Components/Section/Projects/Projects';
export { default as DetailProjects } from '@/Components/Section/Projects/DetailProjects';
export { default as Web } from '@/Components/Section/Projects/Web';
export { default as Mobile } from '@/Components/Section/Projects/Mobile';
export { default as Design } from '@/Components/Section/Projects/Design';
export { default as Contact } from '@/Components/Section/Contact';
export { default as Footer } from '@/Components/Section/Footer';

export { default as TittleSection } from '@/Components/TittleSection';
export { default as Section } from '@/Components/Section';
export { default as ButtonScrollUp } from '@/Components/ButtonScrollUp';